### ISSUE TITLE
module 'allantools' has no attribute 'confidence_intervals'

### ISSUE THREAD

**Issue by motogo** [aewallin/allantools#120]
Confidence intervals worked in allantools 2016.11 but never worked in versions 2019.x

edf = at.edf_greenhall( alpha=0, d=2, m=t, N=len(phase), overlapping = oadev, modified=madev )
(lo,hi) = at.confidence_intervals( dev=dev, ci=0.68268949213708585, edf=edf )

Output in console:
    (lo,hi) = at.confidence_intervals( dev=dev, ci=0.68268949213708585, edf=edf )
AttributeError: module 'allantools' has no attribute 'confidence_intervals'

**Comment by motogo** [comment]
at.confidence_intervals() was renamed in versions 2019 to at.confidence_interval()

why doing such ???

**Comment by fmeynadier** [comment]
As I understand it, confidence intervals in allantools is still a Work In Progress. There has been a major overhaul a while ago, maybe the "s" dropped at some point (willingly or not !).

Anyway thanks for pointing that out. Does it work as expected for you if you replace at.confidence_intervals() with at.confidence_interval() ?

**Comment by aewallin** [comment]
the API (like function names) will change from version to version, sometimes slowly sometimes quickly.
if there are examples in the allantools repo that are broken because of this then please submit a new issue or reopen this one.
if you have scripts that are of general interest then you can submit them for inclusion in a pull-request.
for your own private scripts you just have to update them whenever the API changes - sorry.

closing this for now.

**Comment by motogo** [comment]
Thanks, changed the function name and it is working as expected.
